### ISSUE TITLE
No module named 'lib.utils_mitsubaScene_sample_poses'

### ISSUE THREAD

**Issue by fzy139** [Jerrypiglet/rui-indoorinv-data#1]
Hi,

It seems that this file is missing from the current branch, which is used in sample_poses(). 

Thanks

**Comment by Jerrypiglet** [comment]
Added. Please check again. Thanks for the feedback!

**Comment by fzy139** [comment]
Cool, but the utils_mitsubaScene_scene hasn't been added yet?

**Comment by Jerrypiglet** [comment]
It is added to the 'fipt' branch (other branches are not intended for data in the FIPT paper): https://github.com/Jerrypiglet/rui-indoorinv-data/blob/fipt/lib/utils_mitsubaScene_sample_poses.py

**Comment by fzy139** [comment]
I pull the file you added and I'm at the `fipt` branch. I mean the module`utils_mitsubaScene_scene`which is imported by the file is still missed. [https://github.com/Jerrypiglet/rui-indoorinv-data/blob/5c5825e1fb3766a810ffadc7082e6bc3d72891d8/lib/utils_mitsubaScene_sample_poses.py#L15](line 15)

**Comment by Jerrypiglet** [comment]
This file has just been added. Sorry for the issues... For any future missing files, I apologize and please report here. However you can always (most likely) fine them in the latest branch (`mm1`) although the files maybe untested against `fipt` branch.
