### ISSUE TITLE
Incorrect RAW files for conferenceroom

### ISSUE THREAD

**Issue by zhihao-lin** [Jerrypiglet/rui-indoorinv-data#3]
Hi thanks for your great work! 
I tried to download the data and reproduce the data processing pipeline for real captures.
However I found that the raw_images [here](https://drive.google.com/drive/folders/1taNh8aRNNZd5XIItVyWQQv6u-1lXvHlB?usp=sharing) do not match with the processed images.
Here is one of the example:
scene used in the paper:
![025_0001](https://github.com/Jerrypiglet/rui-indoorinv-data/assets/39002023/c9ddf8da-292c-416d-bde8-b342c09f765c)
RAW images provided:
![img_0221](https://github.com/Jerrypiglet/rui-indoorinv-data/assets/39002023/066aa2ae-66ad-4615-89ec-1434bf571a8b)

We can see that the chairs arrangement and objects on the table look different
Is it possible to get access to the RAW images of conference room that are used in the paper?
Thanks a lot for your help!

**Comment by Jerrypiglet** [comment]
Additional comment as shared with @zhihao-lin :

The released RAW images or ConferenceRoom were from an earlier version thus not correspond to the merged HDR images (.exr images) used in the paper. We lost the RAW images for the ConferenceRoom scene used in the paper. 

The RAW images for ClassRoom should be fine.

Similar scene data can be found in the recent paper [VR-NeRF: High-Fidelity Virtualized Walkable Spaces](https://vr-nerf.github.io/)
 and associated dataset ([facebookresearch/EyefulTower](https://github.com/facebookresearch/EyefulTower)), where they captured similar dataset of higher quality and larger scale. They should be also useable in FIPT and methods of similar settings.
